# Site settings
title: Cheering the Web
email: msantiago1256@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    <em>Cheering the Web</em> is my little piece of the net. As an (overly?) enthusiastic developer, i'll post my thoughts, presentations and ideas here as well as link to any projects I might jump on.Thanks for visiting!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://msantiago1256.github.io" # the base hostname & protocol for your site
twitter_username: msantiago508
github_username:  msantiago1256

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]